import { Injectable } from "@angular/core";
import { SubmissionStatusEnum } from "src/shared/enums/submissionEnum";
import { Submission } from "src/shared/interfaces/submission.interface";

@Injectable({
    providedIn: 'root',
})
export class SubmissionsService {
    private submissionsData: Submission[]  = [
        {
            task: 'Work Flow: Requires Location1',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '156 Wooster St, New York, NY 10012',
            date: new Date(2022, 11, 5, 15, 0),
        },
        {
            task: 'Work Flow: Requires Location2',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit.com',
            address: '665 Broadway, New York, NY 10012',
            date: new Date(2022, 9, 15, 12, 30),
        },
        {
            task: 'Work Flow: Requires Location3',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '25 E 4th St, New York, NY 10003',
            date: new Date(2022, 10, 23, 18, 30),
        },
        {
            task: 'Work Flow: Requires Location4',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '145 2nd Ave, New York, NY 10003',
            date: new Date(2022, 10, 7, 15, 30),
        },
        {
            task: 'Work Flow: Requires Location5',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit1.com',
            address: '298 1st Ave., New York, NY 10009',
            date: new Date(2022, 9, 1, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location6',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit5.com',
            address: '510 E 23rd St, New York, NY 10010',
            date: new Date(2022, 10, 9, 12, 5),
        },
        {
            task: 'Work Flow: Requires Location7',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit2.com',
            address: '271 11th Ave, New York, NY 10001',
            date: new Date(2022, 10, 9, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location8',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit13.com',
            address: '662 9th Ave, New York, NY 10036',
            date: new Date(2022, 9, 11, 6, 50),
        },
        {
            task: 'Work Flow: Requires Location9',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu6.com',
            to: 'tracy@zenduit13.com',
            address: '807 8th Ave, New York, NY 10019',
            date: new Date(2022, 10, 8, 6, 30),
        },

        {
            task: 'Work Flow: Requires Location10',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit13.com',
            address: '810 Seventh Avenue, New York, NY 10019',
            date: new Date(2022, 9, 24, 22, 30),
        },        {
            task: 'Work Flow: Requires Location11',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit2.com',
            address: 'Burlington House, 1343 6th Ave, New York, NY 10105',
            date: new Date(2022, 10, 5, 6, 30),
        },

                {
            task: 'Work Flow: Requires Location12',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit5.com',
            address: 'Дженерал-моторс-билдинг, New York, NY 10022',
            date: new Date(2022, 10, 3, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location13',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '797 Lexington Ave Suite 3R, New York, NY 10002',
            date: new Date(2022, 10, 12, 6, 30),
        },        {
            task: 'Work Flow: Requires Location14',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit6.com',
            address: '1339 York Ave, New York, NY 10021',
            date: new Date(2022, 10, 10, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location15',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit1.com',
            address: '750 Main St, New York, NY 10044',
            date: new Date(2022, 10, 5, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location16',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '2106 30th Ave., Queens, NY 11102',
            date: new Date(2022, 10, 3, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location17',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit1.com',
            address: '26-13 21st St, Long Island City, NY 11102',
            date: new Date(2022, 10, 1, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location18',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit2.com',
            address: '19-15 24th Rd, Queens, NY 11102',
            date: new Date(2022, 10, 26, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location19',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '21-62 28th St, Queens, NY 11105',
            date: new Date(2022, 10, 12, 3, 20),
        },
        {
            task: 'Work Flow: Requires Location20',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit1.com',
            address: '31-07 20th Ave, Queens, NY 11105',
            date: new Date(2022, 10, 18, 12, 30),
        },
        {
            task: 'Work Flow: Requires Location21',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit3.com',
            address: '22-60 78th St, Queens, NY 11370',
            date: new Date(2022, 10, 15, 2, 30),
        },
        {
            task: 'Work Flow: Requires Location22',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit5.com',
            address: '85-05 Astoria Blvd, Queens, NY 11369',
            date: new Date(2022, 10, 6, 6, 40),
        },
        {
            task: 'Work Flow: Requires Location23',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit5.com',
            address: '25-60 90th St, Queens, NY 11369',
            date: new Date(2022, 10, 11, 8, 30),
        },
        {
            task: 'Work Flow: Requires Location24',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit1.com',
            address: '32nd Ave, Flushing, NY 113694',
            date: new Date(2022, 10, 11, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location25',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit2.com',
            address: '86-10 34th Ave, Flushing, NY 11372',
            date: new Date(2022, 10, 21, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location26',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '8215 35th Ave #6g, Queens, NY 11372',
            date: new Date(2022, 10, 28, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location27',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit4.com',
            address: '83-22 37th Ave, Queens, NY 11372',
            date: new Date(2022, 10, 30, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location1',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '156 Wooster St, New York, NY 10012',
            date: new Date(2022, 11, 5, 15, 0),
        },
        {
            task: 'Work Flow: Requires Location2',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit.com',
            address: '665 Broadway, New York, NY 10012',
            date: new Date(2022, 9, 15, 12, 30),
        },
        {
            task: 'Work Flow: Requires Location3',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '25 E 4th St, New York, NY 10003',
            date: new Date(2022, 10, 23, 18, 30),
        },
        {
            task: 'Work Flow: Requires Location4',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '145 2nd Ave, New York, NY 10003',
            date: new Date(2022, 10, 7, 15, 30),
        },
        {
            task: 'Work Flow: Requires Location5',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit1.com',
            address: '298 1st Ave., New York, NY 10009',
            date: new Date(2022, 9, 1, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location6',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit5.com',
            address: '510 E 23rd St, New York, NY 10010',
            date: new Date(2022, 10, 9, 12, 5),
        },
        {
            task: 'Work Flow: Requires Location7',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit2.com',
            address: '271 11th Ave, New York, NY 10001',
            date: new Date(2022, 10, 9, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location8',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit13.com',
            address: '662 9th Ave, New York, NY 10036',
            date: new Date(2022, 9, 11, 6, 50),
        },
        {
            task: 'Work Flow: Requires Location9',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu6.com',
            to: 'tracy@zenduit13.com',
            address: '807 8th Ave, New York, NY 10019',
            date: new Date(2022, 10, 8, 6, 30),
        },

        {
            task: 'Work Flow: Requires Location10',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit13.com',
            address: '810 Seventh Avenue, New York, NY 10019',
            date: new Date(2022, 9, 24, 22, 30),
        },        {
            task: 'Work Flow: Requires Location11',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit2.com',
            address: 'Burlington House, 1343 6th Ave, New York, NY 10105',
            date: new Date(2022, 10, 5, 6, 30),
        },

                {
            task: 'Work Flow: Requires Location12',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit5.com',
            address: 'Дженерал-моторс-билдинг, New York, NY 10022',
            date: new Date(2022, 10, 3, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location13',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '797 Lexington Ave Suite 3R, New York, NY 10002',
            date: new Date(2022, 10, 12, 6, 30),
        },        {
            task: 'Work Flow: Requires Location14',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit6.com',
            address: '1339 York Ave, New York, NY 10021',
            date: new Date(2022, 10, 10, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location15',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit1.com',
            address: '750 Main St, New York, NY 10044',
            date: new Date(2022, 10, 5, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location16',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '2106 30th Ave., Queens, NY 11102',
            date: new Date(2022, 10, 3, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location17',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit1.com',
            address: '26-13 21st St, Long Island City, NY 11102',
            date: new Date(2022, 10, 1, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location18',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit2.com',
            address: '19-15 24th Rd, Queens, NY 11102',
            date: new Date(2022, 10, 26, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location19',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '21-62 28th St, Queens, NY 11105',
            date: new Date(2022, 10, 12, 3, 20),
        },
        {
            task: 'Work Flow: Requires Location20',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit1.com',
            address: '31-07 20th Ave, Queens, NY 11105',
            date: new Date(2022, 10, 18, 12, 30),
        },
        {
            task: 'Work Flow: Requires Location21',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit3.com',
            address: '22-60 78th St, Queens, NY 11370',
            date: new Date(2022, 10, 15, 2, 30),
        },
        {
            task: 'Work Flow: Requires Location22',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit5.com',
            address: '85-05 Astoria Blvd, Queens, NY 11369',
            date: new Date(2022, 10, 6, 6, 40),
        },
        {
            task: 'Work Flow: Requires Location23',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit5.com',
            address: '25-60 90th St, Queens, NY 11369',
            date: new Date(2022, 10, 11, 8, 30),
        },
        {
            task: 'Work Flow: Requires Location24',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit1.com',
            address: '32nd Ave, Flushing, NY 113694',
            date: new Date(2022, 10, 11, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location25',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit2.com',
            address: '86-10 34th Ave, Flushing, NY 11372',
            date: new Date(2022, 10, 21, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location26',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '8215 35th Ave #6g, Queens, NY 11372',
            date: new Date(2022, 10, 28, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location27',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit4.com',
            address: '83-22 37th Ave, Queens, NY 11372',
            date: new Date(2022, 10, 30, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location1',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '156 Wooster St, New York, NY 10012',
            date: new Date(2022, 11, 5, 15, 0),
        },
        {
            task: 'Work Flow: Requires Location2',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit.com',
            address: '665 Broadway, New York, NY 10012',
            date: new Date(2022, 9, 15, 12, 30),
        },
        {
            task: 'Work Flow: Requires Location3',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '25 E 4th St, New York, NY 10003',
            date: new Date(2022, 10, 23, 18, 30),
        },
        {
            task: 'Work Flow: Requires Location4',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '145 2nd Ave, New York, NY 10003',
            date: new Date(2022, 10, 7, 15, 30),
        },
        {
            task: 'Work Flow: Requires Location5',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit1.com',
            address: '298 1st Ave., New York, NY 10009',
            date: new Date(2022, 9, 1, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location6',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit5.com',
            address: '510 E 23rd St, New York, NY 10010',
            date: new Date(2022, 10, 9, 12, 5),
        },
        {
            task: 'Work Flow: Requires Location7',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit2.com',
            address: '271 11th Ave, New York, NY 10001',
            date: new Date(2022, 10, 9, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location8',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit13.com',
            address: '662 9th Ave, New York, NY 10036',
            date: new Date(2022, 9, 11, 6, 50),
        },
        {
            task: 'Work Flow: Requires Location9',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu6.com',
            to: 'tracy@zenduit13.com',
            address: '807 8th Ave, New York, NY 10019',
            date: new Date(2022, 10, 8, 6, 30),
        },

        {
            task: 'Work Flow: Requires Location10',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit13.com',
            address: '810 Seventh Avenue, New York, NY 10019',
            date: new Date(2022, 9, 24, 22, 30),
        },        {
            task: 'Work Flow: Requires Location11',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit2.com',
            address: 'Burlington House, 1343 6th Ave, New York, NY 10105',
            date: new Date(2022, 10, 5, 6, 30),
        },

                {
            task: 'Work Flow: Requires Location12',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu5.com',
            to: 'tracy@zenduit5.com',
            address: 'Дженерал-моторс-билдинг, New York, NY 10022',
            date: new Date(2022, 10, 3, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location13',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit.com',
            address: '797 Lexington Ave Suite 3R, New York, NY 10002',
            date: new Date(2022, 10, 12, 6, 30),
        },        {
            task: 'Work Flow: Requires Location14',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit6.com',
            address: '1339 York Ave, New York, NY 10021',
            date: new Date(2022, 10, 10, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location15',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit1.com',
            address: '750 Main St, New York, NY 10044',
            date: new Date(2022, 10, 5, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location16',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '2106 30th Ave., Queens, NY 11102',
            date: new Date(2022, 10, 3, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location17',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit1.com',
            address: '26-13 21st St, Long Island City, NY 11102',
            date: new Date(2022, 10, 1, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location18',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit2.com',
            address: '19-15 24th Rd, Queens, NY 11102',
            date: new Date(2022, 10, 26, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location19',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '21-62 28th St, Queens, NY 11105',
            date: new Date(2022, 10, 12, 3, 20),
        },
        {
            task: 'Work Flow: Requires Location20',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit1.com',
            address: '31-07 20th Ave, Queens, NY 11105',
            date: new Date(2022, 10, 18, 12, 30),
        },
        {
            task: 'Work Flow: Requires Location21',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit3.com',
            address: '22-60 78th St, Queens, NY 11370',
            date: new Date(2022, 10, 15, 2, 30),
        },
        {
            task: 'Work Flow: Requires Location22',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu3.com',
            to: 'tracy@zenduit5.com',
            address: '85-05 Astoria Blvd, Queens, NY 11369',
            date: new Date(2022, 10, 6, 6, 40),
        },
        {
            task: 'Work Flow: Requires Location23',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit5.com',
            address: '25-60 90th St, Queens, NY 11369',
            date: new Date(2022, 10, 11, 8, 30),
        },
        {
            task: 'Work Flow: Requires Location24',
            status: SubmissionStatusEnum.LOW,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit1.com',
            address: '32nd Ave, Flushing, NY 113694',
            date: new Date(2022, 10, 11, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location25',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu2.com',
            to: 'tracy@zenduit2.com',
            address: '86-10 34th Ave, Flushing, NY 11372',
            date: new Date(2022, 10, 21, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location26',
            status: SubmissionStatusEnum.UNCOMPLETE,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit3.com',
            address: '8215 35th Ave #6g, Queens, NY 11372',
            date: new Date(2022, 10, 28, 6, 30),
        },
        {
            task: 'Work Flow: Requires Location27',
            status: SubmissionStatusEnum.UNASSIGNED,
            from: 'zendu@zendu1.com',
            to: 'tracy@zenduit4.com',
            address: '83-22 37th Ave, Queens, NY 11372',
            date: new Date(2022, 10, 30, 6, 30),
        }
    ]


    public getSubmissions(): Submission[] {
        return this.submissionsData
    }
}